### ISSUE TITLE
The lava in the stone barrel does not seem to be filled up to be converted to obsidian

### ISSUE THREAD

**Issue by DancingSnow0517** [NovaMachina/ExNihiloSequentia#108] opened 2021-02-16 10:52 UTC
**Describe the bug**
I used create fluid pipe to add lava to stone barrel and water on top.Lava doesn't full and right click on it can get obsidian

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.0.15
Ex Nihilo: Sequentia Version: 2021-2-10

**Comment by Jkosio23** [comment] 2021-02-17 19:46
Do you have anything pulling items out of the barrel, because if so this is a duplicate of #103

**Comment by NovaMachina** [comment] 2021-02-19 04:53
Duplicate of #103

**Closed as completed by NovaMachina** 2021-02-19 04:53 UTC
Labels: bug
