### ISSUE TITLE
[BUG] <title> bug ex nihilo version 1.21

### ISSUE THREAD

**Issue by CelyanRbx** [NovaMachina/ExNihiloSequentia#468] opened 2024-08-13 09:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

bug ex nihilo

### Expected Behavior

a new version of the mod to make it work

### Steps to Reproduce

1. 'look at the problem'
2. 'the repaired'
3. 'to update'

### Minecraft Version

1.20.X

### Forge Version

1.21 Neoforge  21.0.167

### Ex Nihilo: Sequentia Version

7.0.0-build.1-beta

### Additional Context

https://haste.zendrique.fr/genukibalu.apache

### Log File

[[java.lang.NoSuchMethodError: 'void net.neoforged.neoforge.common.ModConfigSpec.setConfig(com.electronwill.nightconfig.core.CommentedConfig)'
	at TRANSFORMER/exnihilosequentia@7.0.0/novamachina.exnihilosequentia.common.Config.loadConfig(Config.java:682) ~[ExNihiloSequentia-1.21-7.0.0-build.1-beta.jar%23304!/:1.21-7.0.0-build.1-beta]
	at TRANSFORMER/exnihilosequentia@7.0.0/novamachina.exnihilosequentia.ExNihiloSequentia.<init>(ExNihiloSequentia.java:51) ~[ExNihiloSequentia-1.21-7.0.0-build.1-beta.jar%23304!/:1.21-7.0.0-build.1-beta]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:115) ~[loader-4.0.23.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153) ~[loader-4.0.23.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-4.0.23.jar%2360!/:4.0]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
[13août2024 10:56:14.344] [modloading-worker-0/INFO] [PluginManager/]: Scanning classes for titanium
[13août2024 10:56:14.542] [modloading-worker-0/INFO] [net.permutated.pylons.Pylons/]: Registering mod: pylons
[13août2024 10:56:14.714] [modloading-worker-0/INFO] [me.treyruffy.betterf3.BetterF3NeoForge/]: [BetterF3] Starting...
[13août2024 10:56:14.714] [modloading-worker-0/WARN] [me.treyruffy.betterf3.BetterF3NeoForge/]: [BetterF3] Not supported on dedicated server!
[13août2024 10:56:14.735] [modloading-worker-0/INFO] [be.florens.expandability.ExpandAbility/]: ExpandAbility here, who dis?
[13août2024 10:56:14.784] [modloading-worker-0/INFO] [PluginManager/]: Scanning classes for functionalstorage
[13août2024 10:56:16.545] [modloading-worker-0/INFO] [Modern Industrialization/]: Modern Industrialization setup done!
[13août2024 10:56:17.550] [main/FATAL] [net.neoforged.fml.ModLoader/LOADING]: Failed to wait for future Mod Construction, 1 errors found
[13août2024 10:56:17.848] [main/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID a91397e1-87c5-4e37-a760-575154500a28
[13août2024 10:56:17.849] [main/FATAL] [net.neoforged.neoforge.server.loading.ServerModLoader/]: Crash report saved to ./crash-reports/crash-2024-08-13_10.56.17-fml.txt
[13août2024 10:56:17.855] [main/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID e052c90c-5a80-40b0-a127-2ebffa5cd545
[13août2024 10:56:17.859] [main/ERROR] [net.minecraft.server.Main/FATAL]: Failed to start the minecraft server
net.neoforged.fml.ModLoadingException: Loading errors encountered:
	- Ex Nihilo: Sequentia (exnihilosequentia) has failed to load correctly
	  java.lang.NoSuchMethodError: 'void net.neoforged.neoforge.common.ModConfigSpec.setConfig(com.electronwill.nightconfig.core.CommentedConfig)'
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModLoader.waitForFuture(ModLoader.java:281) ~[loader-4.0.23.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModLoader.dispatchParallelTask(ModLoader.java:244) ~[loader-4.0.23.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModLoader.constructMods(ModLoader.java:152) ~[loader-4.0.23.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:142) ~[loader-4.0.23.jar%2360!/:4.0]
	at TRANSFORMER/neoforge@21.0.167/net.neoforged.neoforge.internal.CommonModLoader.begin(CommonModLoader.java:49) ~[neoforge-21.0.167-universal.jar%23252!/:?]
	at TRANSFORMER/neoforge@21.0.167/net.neoforged.neoforge.server.loading.ServerModLoader.load(ServerModLoader.java:34) ~[neoforge-21.0.167-universal.jar%23252!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.Main.main(Main.java:124) ~[server-1.21-20240613.152323-srg.jar%23251!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.23.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128) ~[loader-4.0.23.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:32) ~[loader-4.0.23.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.23.jar%2360!/:4.0]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%2362!/:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]](https://haste.zendrique.fr/genukibalu.apache)
](https://haste.zendrique.fr/genukibalu.apache)

**Comment by NovaMachina** [comment] 2024-08-13 12:34
Duplicate of #466

**Closed as completed** 2024-08-13 12:34 UTC
Labels: bug
