### ISSUE TITLE
Infinite Gravel, Sand, Dust

### ISSUE THREAD

**Issue by Lolam33** [NovaMachina/ExNihiloSequentia#144] opened 2021-03-06 20:14 UTC
**Describe the bug**
When you have 1 stack of Gravel, Sand or Dust in the inventory (otherwise full inventory) and 1 stack of the same material on the sieve and start sifting you will get unlimited refills of the material.

**To Reproduce**
1. Put an item in every slot of your inventory
2. Take 2 stacks of a sievable item
3. Put 1 stack in your inventory and 1 stack on the sieve
4. Start sieving
5. The Gravel, Sand or Dust will now refill infinitely and you can sieve forever.

**Expected behavior**
The items on the ground should refill your inventory, but should decrease. 

**Screenshots**
![2021-03-06_21 02 09](https://user-images.githubusercontent.com/80175154/110219614-ad39d080-7ec0-11eb-8b96-69ab8b44ab4b.png)
![2021-03-06_21 01 50](https://user-images.githubusercontent.com/80175154/110219619-af9c2a80-7ec0-11eb-844b-9d3d554be314.png)
![2021-03-06_21 01 53](https://user-images.githubusercontent.com/80175154/110219621-b034c100-7ec0-11eb-82c5-06ba22d585da.png)
![2021-03-06_21 02 05](https://user-images.githubusercontent.com/80175154/110219626-b165ee00-7ec0-11eb-8ba4-98b20d6f2375.png)

After sieving and refilling its still 64 sand on the ground
![2021-03-06_21 01 36](https://user-images.githubusercontent.com/80175154/110219617-ae6afd80-7ec0-11eb-98cf-f7ca60834bde.png)

**Version**
Minecraft Version: 1.16.4
Forge Version: 35.1.37
Ex Nihilo: Sequentia Version: 1.16-2.0.2.0

**Comment by Irgendwer01** [comment] 2021-03-06 20:18
@Lolam33 Duplicate of #120

**Closed as completed** 2021-03-06 20:27 UTC
Labels: bug
