### ISSUE TITLE
(1.16) CraftTweaker integration for crooking is broken

### ISSUE THREAD

**Issue by pm065** [NovaMachina/ExNihiloSequentia#169] opened 2021-04-01 18:31 UTC
The CraftTweaker integration for crooking is broken. Original and full report on CraftTweaker github (was told to bring it here, and I don't want to type a full report all over again):
https://github.com/CraftTweaker/CraftTweaker/issues/1226

**Comment by NovaMachina** [comment] 2021-04-01 18:33
Duplicate of #158.

**Closed as completed by NovaMachina** 2021-04-01 18:33 UTC
Labels: bug
