### ISSUE TITLE
Error during loading

### ISSUE THREAD

**Issue by sz55net** [NovaMachina/ExNihiloSequentia#101] opened 2021-02-09 17:04 UTC
**Describe the bug**
When I am loading the Sky Bees modpack, it crashes.

**To Reproduce**
1. Launch Sky Bees modpack

**Expected behavior**
It launches.

**Screenshots**
N/A

**Version**
Minecraft Version: 1.16.4
Forge Version: 35.1.37
Ex Nihilo: Sequentia Version: 2.0.1.0

**Additional context**
[https://pastebin.com/CA9neKWX](https://pastebin.com/CA9neKWX)

**Comment by NovaMachina** [comment] 2021-02-09 17:07
Duplicate of #94

**Closed as completed by NovaMachina** 2021-02-09 17:07 UTC
Labels: bug
