### ISSUE TITLE
[BUG] Obsidian Transformation Broken

### ISSUE THREAD

**Issue by allanf181** [NovaMachina/ExNihiloSequentia#471] opened 2024-09-27 22:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/user-attachments/assets/233eadc5-6da9-4ebb-b76c-ad11076463ee)
The stone barrel is filled with a block of air
Same of #103

### Expected Behavior

Stone barrels make obsidian

### Steps to Reproduce

Just set up the obsian recipe automatically, with blocks that transport fluids and items in 1 tick, using for example the cyclic hopper or the io laser with maximum upgrades

### Minecraft Version

1.20.X

### Forge Version

47.3.7

### Ex Nihilo: Sequentia Version

5.0.0.0

### Additional Context

I believe that the solution in 1.16.5 applies in this case
https://github.com/NovaMachina-Mods/ExNihiloSequentia/blob/1.20/src/main/java/novamachina/exnihilosequentia/world/item/crafting/SolidifyingRecipe.java#L64-L66

### Log File

I'm playing on a server, so I don't have access to its logs.

**Comment by allanf181** [comment] 2024-09-28 04:14
https://github.com/NovaMachina-Mods/ExNihiloSequentia/blob/1.20/src/main/java/novamachina/exnihilosequentia/common/registries/SolidifyingRegistry.java#L54-L57
`return this.getResultItem(fluidInTank, fluidOnTop).copy()` solves the issue, I tested it by writing a mixin

**Comment by remplerus** [comment] 2024-09-30 23:12
I can't reproduce the bug rn (due to limited time) but your solution might work. could you contact me on discord and i would give you a pre-release file to verify that your solution works.

**Comment by JesperKuipers** [comment] 2024-11-21 20:22
having the same problem but trying to make cobblestone

**Comment by remplerus** [comment] 2024-12-14 16:37
fixed in build 10

**Closed as completed by remplerus** 2024-12-14 16:37 UTC
Labels: bug, considering, 1.20
