### ISSUE TITLE
Skybees error code 255

### ISSUE THREAD

**Issue by StealthHydra179** [NovaMachina/ExNihiloSequentia#148] opened 2021-03-07 22:50 UTC
**Describe the bug**

**To Reproduce**
1. Place block '...'
2. Right click on '...'
3. Do thing '...'
Download Skybees from curseforge, run it.

**Expected behavior**
run? open? not crash?

**Screenshots**
![image](https://user-images.githubusercontent.com/47306082/110257340-7cfb3c00-7f6b-11eb-9833-d32cf3f311db.png)
[crash-2021-03-07_17.17.41-client.txt](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/6098092/crash-2021-03-07_17.17.41-client.txt)

**Version**
Minecraft Version: 1.16.4
Forge Version: 35.1.37
Ex Nihilo: Sequentia Version: "exnihilosequentia-1.16-2.0.2.0.jar"

**Additional context**
Stack traces and log files are nice to have. Submit all files through [Gist](https://gist.github.com/) or [Pastebin](https://pastebin.com/) and place the links here.
Looks similar to [this issue](https://github.com/NovaMachina-Mods/ExNihiloSequentia/issues/135) but the error is different. Not sure if i'm doing something wrong.

**Comment by NovaMachina** [comment] 2021-03-07 23:33
Duplicate of #119. Please update the Mekanism Addon where the bug exists.

**Closed as completed by NovaMachina** 2021-03-07 23:33 UTC
Labels: bug
