### ISSUE TITLE
Mekanism's logistic transporter and barrel

### ISSUE THREAD

**Issue by Pupun2542** [NovaMachina/ExNihiloSequentia#145] opened 2021-03-07 06:42 UTC
when I use Mekansim's logistic transporter input seeds into barrels they didn't consume any seeds but they do produce dirt for me. I don't know where to report this bug so I decided to report both Ex Nihilo and Mekanism.

Thank you

**Comment by Pupun2542** [comment] 2021-03-07 08:50
Release 1.16.5-forge-36.0.43
Mekanism-1.16.5-10.0.21.448
exnihilosequentia-1.16-2.0.2.3

Steps to reproduce:
1. Place a barrel and 2 chest
2. Connect chests and barrel with logistical transporter input a stack or two any seeds
3. Quit the world and enter it again

**Comment by remplerus** [comment] 2021-03-07 11:44
couldnt reproduce that exact bug, but the barrel uses "virtual" saplings that it shouldnt have.
E.g. for 3 dirt, it uses not 24 saplings. it uses (depends on pipe) between 4 and 24 saplings, but never exact 24 saplings.

**Comment by NovaMachina** [comment] 2021-04-17 02:52
Should be fixed in latest version.

**Closed as completed by NovaMachina** 2021-04-17 02:52 UTC
